"""
One-command training script.

Usage:
  python -m backend.ml.training.train_all

Trains the three models in sequence (risk classifier → anomaly autoencoder →
intent classifier), saves all artefacts to backend/models/, prints a summary,
and writes backend/models/MODEL_CARDS.md describing each model.
"""

from __future__ import annotations

import json
import os
import time

from ..registry import MODELS_DIR
from .train_anomaly_detector import main as train_anomaly
from .train_intent_classifier import main as train_intent
from .train_risk_classifier import main as train_risk


MODEL_CARDS_TEMPLATE = """# PulseGuard AI — Model Cards

This file is auto-generated by `python -m backend.ml.training.train_all`.
Each model was trained from scratch on synthetic-but-clinically-grounded
data and is loaded by the Flask backend at startup.

## 1. Risk Classifier

* **Task**: predict patient risk level (`normal` / `warning` / `high`) from 6 vitals.
* **Architecture**: `StandardScaler → MLP(64-32-16, ReLU) → Softmax(3)`. Loss: cross-entropy. Optimizer: Adam.
* **Training data**: {risk_train} synthetic samples drawn from 11 clinical scenarios; labels distilled from the production rule engine (knowledge-distillation setup).
* **Test accuracy**: **{risk_acc}** on {risk_test} held-out samples.
* **Trained in**: {risk_time}s, {risk_iter} epochs (early stopping, patience 10).
* **Where used**: every `POST /api/telemetry` ingest returns `analysis.ml_risk = {{label, confidence, probabilities}}` alongside the rule-engine output.

## 2. Anomaly Autoencoder

* **Task**: flag telemetry readings that deviate from the healthy training distribution.
* **Architecture**: bottleneck `MLPRegressor(6→4→2→4→6, ReLU)`. Trained as an autoencoder (input = target). Loss: MSE.
* **Training data**: {anom_train} samples drawn ONLY from `resting`/`light_walk`/`sleep` scenarios — so the network has never seen abnormal data.
* **Detection threshold**: 99th percentile of training reconstruction error = **{anom_thresh}**.
* **Evaluation**: AUC for separating normal vs abnormal (warning + high) readings = **{anom_auc}**. Recall on abnormal at the chosen threshold = **{anom_recall}**.
* **Trained in**: {anom_time}s, {anom_iter} epochs.
* **Where used**: every `POST /api/telemetry` ingest returns `analysis.ml_anomaly = {{score, is_anomaly}}`.

## 3. Intent Classifier

* **Task**: classify chatbot user messages into one of 13 intents (status_check, metric_query, symptom_query, tip_request, emergency, ...).
* **Architecture**: `TF-IDF (word 1-2 + char 2-4) → MLP(64-32, ReLU) → Softmax(13)`. Loss: cross-entropy. Optimizer: Adam.
* **Training data**: {intent_train} hand-authored + augmented examples across 13 intents.
* **Test accuracy**: **{intent_acc}** on {intent_test} held-out examples.
* **Trained in**: {intent_time}s, {intent_iter} epochs.
* **Where used**: every `POST /api/chat` first asks the trained classifier for an intent. If the classifier's confidence is low (< 0.45) or the regex NLU detects an emergency keyword, the regex NLU wins. This is a "neural with safety override" hybrid.

## Reproducibility

```bash
python -m backend.ml.training.train_all
```

Everything is deterministic (`seed=42`), takes ~30-60 seconds on a modern
CPU, and produces the artefacts under `backend/models/`. Metrics JSON files
live next to each model.
"""


def main():
    os.makedirs(MODELS_DIR, exist_ok=True)
    print("=" * 60)
    print("PulseGuard AI — training all neural models")
    print("=" * 60)
    t0 = time.time()

    risk_metrics = train_risk()
    print()
    anom_metrics = train_anomaly()
    print()
    intent_metrics = train_intent()

    total = time.time() - t0
    summary = {
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "total_seconds": round(total, 2),
        "models": {
            "risk_classifier": {
                "test_accuracy": risk_metrics["test_accuracy"],
                "train_seconds": risk_metrics["train_seconds"],
                "n_iterations": risk_metrics["n_iterations"],
            },
            "anomaly_autoencoder": {
                "auc": anom_metrics["test"]["auc_normal_vs_abnormal"],
                "train_seconds": anom_metrics["train_seconds"],
                "n_iterations": anom_metrics["n_iterations"],
            },
            "intent_classifier": {
                "test_accuracy": intent_metrics["test_accuracy"],
                "train_seconds": intent_metrics["train_seconds"],
                "n_iterations": intent_metrics["n_iterations"],
            },
        },
    }
    with open(os.path.join(MODELS_DIR, "training_summary.json"), "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    # Write model cards
    cards = MODEL_CARDS_TEMPLATE.format(
        risk_train=risk_metrics["training_samples"],
        risk_test=risk_metrics["test_samples"],
        risk_acc=risk_metrics["test_accuracy"],
        risk_time=risk_metrics["train_seconds"],
        risk_iter=risk_metrics["n_iterations"],
        anom_train=anom_metrics["training_samples"],
        anom_thresh=anom_metrics["threshold_p99"],
        anom_auc=anom_metrics["test"]["auc_normal_vs_abnormal"],
        anom_recall=anom_metrics["test"]["abnormal_recall_at_threshold"],
        anom_time=anom_metrics["train_seconds"],
        anom_iter=anom_metrics["n_iterations"],
        intent_train=intent_metrics["train_samples"],
        intent_test=intent_metrics["test_samples"],
        intent_acc=intent_metrics["test_accuracy"],
        intent_time=intent_metrics["train_seconds"],
        intent_iter=intent_metrics["n_iterations"],
    )
    with open(os.path.join(MODELS_DIR, "MODEL_CARDS.md"), "w", encoding="utf-8") as f:
        f.write(cards)

    print()
    print("=" * 60)
    print(f"Training complete in {total:.1f}s")
    print(f"  RiskClassifier      acc = {risk_metrics['test_accuracy']}")
    print(f"  AnomalyAutoencoder  auc = {anom_metrics['test']['auc_normal_vs_abnormal']}")
    print(f"  IntentClassifier    acc = {intent_metrics['test_accuracy']}")
    print(f"Artefacts saved to: {MODELS_DIR}/")
    print(f"Model cards:        {os.path.join(MODELS_DIR, 'MODEL_CARDS.md')}")
    print("=" * 60)


if __name__ == "__main__":
    main()
