# -*- coding: utf-8 -*-
"""chatbot kaggle notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13G56z3dV4mMbT-9O4UtXQnyJ4p8i5-Zw
"""

!pip install -q transformers datasets peft accelerate bitsandbytes trl

import numpy as np
import pandas as pd
import torch
import random
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    Trainer
)
from peft import LoraConfig, get_peft_model

def generate_synthetic_sample():

    hr = random.randint(50, 160)
    spo2 = random.randint(80, 100)
    temp = round(random.uniform(35.0, 40.0), 1)
    activity = random.randint(0, 3)  # 0=rest, 3=high activity

    return hr, spo2, temp, activity

def medical_assessment(hr, spo2, temp, activity):

    assessment = []
    risk = "Low"

    if hr > 120:
        assessment.append("tachycardia detected")
        risk = "High"

    elif hr < 55:
        assessment.append("bradycardia detected")
        risk = "Medium"

    if spo2 < 90:
        assessment.append("hypoxia detected")
        risk = "High"

    if temp > 38.5:
        assessment.append("fever detected")
        if risk != "High":
            risk = "Medium"

    if activity == 0 and hr > 110:
        assessment.append("elevated heart rate at rest")
        risk = "High"

    if len(assessment) == 0:
        assessment.append("vital signs within normal range")

    return risk, ", ".join(assessment)

data = []

for _ in range(5000):
    hr, spo2, temp, activity = generate_synthetic_sample()
    risk, assessment = medical_assessment(hr, spo2, temp, activity)

    input_text = f"""
Heart rate: {hr} bpm
SpO2: {spo2}%
Temperature: {temp} C
Activity level: {activity}
Provide medical assessment.
"""

    output_text = f"""
Risk Level: {risk}
Assessment: {assessment}.
Recommendation: Seek medical attention if symptoms persist.
"""

    data.append({
        "text": input_text + output_text
    })

df = pd.DataFrame(data)
dataset = Dataset.from_pandas(df)

print(dataset[0])

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Proper quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj","v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

def tokenize(example):
    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

    tokens["labels"] = tokens["input_ids"].copy()

    return tokens

tokenized_dataset = dataset.map(
    tokenize,
    batched=True,
    remove_columns=dataset.column_names
)

training_args = TrainingArguments(
    output_dir="./medical_slm",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    num_train_epochs=3,
    fp16=True,
    logging_steps=20,
    save_strategy="epoch",
    report_to="none"
)

model.config.use_cache = False

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset
)

trainer.train()

trainer.save_model("./medical_slm_final")
tokenizer.save_pretrained("./medical_slm_final")

prompt = """
Heart rate: 135 bpm
SpO2: 85%
Temperature: 39.0 C
Activity level: 0
Provide medical assessment.
"""

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

output = model.generate(
    **inputs,
    max_new_tokens=150,
    temperature=0.3
)

print(tokenizer.decode(output[0], skip_special_tokens=True))